

services:
  db:
    image: postgres:latest
    container_name: prospecfy-db
    restart: always
    shm_size: '128mb'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
    driver: local